#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, in1,		 LightSensor,		 sensorNone)
#pragma config(Sensor, in2,		 LineFollower1,	 sensorLineFollower)
#pragma config(Sensor, in3,		 LineFollower2,	 sensorLineFollower)
#pragma config(Sensor, in4,		 Linefollower3,	 sensorLineFollower)
#pragma config(Sensor, in5,		 Potentiometer,	 sensorPotentiometer)
#pragma config(Sensor, in6,		 Gyro,					 sensorGyro)
#pragma config(Sensor, dgtl1,	 encoderR,			 sensorQuadEncoder)
#pragma config(Sensor, dgtl3,	 encoderL,			 sensorQuadEncoder)
#pragma config(Sensor, dgtl5,	 Sonar,					 sensorSONAR_cm)
#pragma config(Sensor, dgtl7,	 limmitSW,			 sensorTouch)
#pragma config(Sensor, dgtl8,	 button,				 sensorTouch)
#pragma config(Motor,	 port2,						motorR,				 tmotorVex269, openLoop)
#pragma config(Motor,	 port3,						motorL,				 tmotorVex269, openLoop, reversed)
#pragma config(Motor,	 port4,						arm,					 tmotorVex269, openLoop)
#pragma config(Motor,	 port5,						speedC,				 tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                           - Dual Joystick Control with Arm - 2 Remotes -                           *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses the Left and the Right joysticks on Remote Control 1 to run the robot using     *|
|*  "tank control". The Group 6 buttons on the top-right of Remote Control 2 are used to raise and    *|
|*  lower the arm.                                                                                    *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
|*    Motor - Port 6          armMotor             VEX Motor           Arm motor                      *|
\*----------------------------------------------------------------------------------------------------*/
task display(){
	bLCDBacklight = true;
	string mainBattery, backupBattery;

	while(true)
	{
		clearLCDLine(0);
		clearLCDLine(1);

		//Display the Primary Robot battery voltage
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);

		//Display the Backup battery voltage
		displayLCDString(1, 0, "Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
		displayNextLCDString(backupBattery);

		//Short delay for the LCD refresh rate
		wait1Msec(100);
	}
}



//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++



task main()
{
	StartTask(display);
  while(1 == 1)
  {
    //Driving Motor Control with Remote Control 1
    motor[motorL] = vexRT[Ch3] / 2;
    motor[motorR] = vexRT[Ch2] / 2;

    //Arm open close
    if(vexRT[Btn6U] == 1)
    {
      motor[arm] = 40;
    }
    else if(vexRT[Btn6D] == 1)
    {
      motor[arm] = -20;
    }
    else
    {
      motor[arm] = 0;
    }
    //Arm up down
    if(vexRT[Btn5D] == 1)
    {
      motor[speedC] = 20;
    }
    else if(vexRT[Btn5U] == 1)
    {
      motor[speedC] = -40;
    }
    else
    {
      motor[speedC] = 0;
    }


  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
