#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, in2,    lineFollowerLeft, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerCenter, sensorLineFollower)
#pragma config(Sensor, in4,    lineFollowerRight, sensorLineFollower)
#pragma config(Sensor, in5,    Potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in6,    Gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  encoderR,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderL,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  Sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  limmitSW,       sensorTouch)
#pragma config(Sensor, dgtl8,  button,         sensorTouch)
#pragma config(Motor,  port2,           motorR,        tmotorVex269, openLoop)
#pragma config(Motor,  port3,           motorL,        tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port4,           arm,           tmotorVex269, openLoop)
#pragma config(Motor,  port5,           speedC,        tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                             	    - Triple Sensor Line Tracking -                                   *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program uses 3 VEX Line Follower Sensors to track a black line on a light(er) surface.       *|
|*  There is a two second pause at the beginning of the program.                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Lighting conditions, line darkness, and surface lightness change from place to place,       *|
|*        so the value of 'threshold' may need to be changed to better suit your environment.         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor  - Port 2     rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor  - Port 3     leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Analog - Port 1     lineFollowerRIGHT   VEX Light Sensor      Front-right, facing down          *|
|*    Analog - Port 2     lineFollowerCENTER  VEX Light Sensor      Front-center, facing down         *|
|*    Analog - Port 3     lineFollowerLEFT    VEX Light Sensor      Front-left, facing down           *|
\*-----------------------------------------------------------------------------------------------4246-*/

//white right 1880/ black right 2846/ (1880 + 2846)/2=2363
//white centere 1418/ black center	2770/ (1418+2770)/2=2094
//white left 2112/ black left	2872/	(2112+2872)/2=2492
// (2363+2094+2492)/3=2316
//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
int threshold = 2316;
task stopMyTask() {
	while(vexRT[Btn8R]==0){
	}
	StopAllTasks();
}
bool left=false;
bool right=false;

void find_line(){
	if(left==true){
		while(SensorValue(lineFollowerCenter) < threshold){
			motor[motorL]  = 0;
			motor[motorR] = 63;
			left=false;
		}
	}
	if(right==true){

		while(SensorValue(lineFollowerCenter) < threshold){
		motor[motorL]  = 63;
		motor[motorR] = 0;
		right=false;
		}
	}
}

task main()
{
	StartTask(stopMyTask);
	wait1Msec(2000);          // The program waits for 2000 milliseconds before continuing.

	      /* found by taking a reading on both DARK and LIGHT    */
	/* surfaces, adding them together, then dividing by 2. */
	while(true)
	{
		// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -+
		displayLCDCenteredString(0, "LEFT  CNTR  RGHT");        //  Display   |
		displayLCDPos(1,0);                                     //  Sensor    |
		displayNextLCDNumber(SensorValue(lineFollowerLeft));    //  Readings  |
		displayLCDPos(1,6);                                     //  to LCD.   |
		displayNextLCDNumber(SensorValue(lineFollowerCenter));  //            |
		displayLCDPos(1,12);                                    //  L  C  R   |
		displayNextLCDNumber(SensorValue(lineFollowerRight));   //  x  x  x   |
		// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -+

		// RIGHT sensor sees dark:
		if(SensorValue(lineFollowerRight) > threshold && SensorValue(lineFollowerCenter) < threshold)
		{
			// counter-steer right:
			motor[motorL]  = 63;
			motor[motorR] = 0;
			right=true;
			left=false;
		}

		// CENTER sensor sees dark:
		if(SensorValue(lineFollowerCenter) > threshold)
		{
			// go straight
			motor[motorL]  = 63;
			motor[motorR] = 63;
		}
		// LEFT sensor sees dark:
		if(SensorValue(lineFollowerLeft) > threshold && SensorValue(lineFollowerCenter) < threshold)
		{
			// counter-steer left:
			motor[motorL]  = 0;
			motor[motorR] = 63;
			left=true;
			right=false;
		}

		else{
			find_line();
		}

	}
}
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
